import os, glob, sys
env = Environment()

# Short messages while compiling and linking.
env.Append(CXXCOMSTR = "Compiling static object $TARGET")
env.Append(LINKCOMSTR = "Linking $TARGET")
env.Append(SHCXXCOMSTR = "Compiling shared object $TARGET")
env.Append(SHLINKCOMSTR = "Linking shared $TARGET" )


# CXXFLAGS
if ARGUMENTS.get('debug', 0):
    env.Append(CXXFLAGS = ['-g'])
    build_dir = 'debug/'
else:
    build_dir = 'release/'

env.BuildDir(build_dir, 'src/', duplicate=0)

env.Append(CXXFLAGS = ['-march=native','-Wno-write-strings','-D__STDC_CONSTANT_MACROS'])
env.Append(LINKFLAGS = ['-Wl,--no-undefined'])


# Headers and libs
env['CPPPATH'] = [ build_dir,
				  'src',
                  '../src',
                  '../',
                  '/usr/include/opencv', '/usr/local/include/opencv',
                  '/usr/local/include/boost'
		  './'
                  '.']

env['LIBPATH'] = ['/usr/local/lib',
                  '/usr/lib',
				  './']

env['LIBS'] = [
    'opencv_core',
    'opencv',
    'cvaux',
    'boost_program_options',
    'mysqlclient',
    'jpeg',
    'z'
]

# Common sources.
# common_src = env.Glob( build_dir + '*.cpp')

zoneminder_src =  env.Glob('../src/' + 'zm_detector.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_poly.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_zone.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_image.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_db.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_debug.c')
zoneminder_src += env.Glob('../src/' + 'zm_config.cpp')
zoneminder_src += env.Glob('../src/' + 'zm_jpeg.c')


# Face detector sources.
face_haar_src = env.Glob( build_dir + 'face_detector_plugin.cpp')

# Shared lib
env.SharedLibrary(target = 'zm_plugin_face_haar', source = [face_haar_src, zoneminder_src])

